language: java
sudo: false

jdk:
  - oraclejdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: "ahoEwkAd6BxFocCAu7DFnFf5EZFRWayK+WJ3JQ6KefU/F66AqJkrZeqChEwrdGCMSEU4kC3reYVTCu07e9kUPb5TIAmvQ6ER56AH7AWZ8Gxyp84QJnuJ6PaPUNza25SuZRy0oLzkPETXeUOqVDlH/7BqQJ7SYkQzMhTk8Sr3KTbA8Nbz9TakMgRJUNn2SIWjg6Z8qKbuKGywi/Ax18OaQnccQkVnFp3qPasDK4mfYuYapgbBSK08rDOMHFzxgR0CvcJKW2WTgE0n4T9AWouX+4mpy/Fm6RppZx7cLeWnhDYZv/hbK8EG6mw/oGoKONj3e3v4w2oMOtroI60U0IT9pmErLYsb/evrIqoypN8UfDjHG8DsJ7hzp5BYZlMbb+vuPUsaZQFG1kPdrCzB3ZD530WC/mHxI3XS3Hy0YfylR6CYhmNjrVbt4UBDiv071KyvSrj3nmXiGBFggQ/GhcEIy9rQRDPZUWBGgDmXrNFsPwzdSWRobpRsGn/VOKoncE85fssRtJockiKkrA4bT68hZzHxrSRPUwlCm/pvhZjTmre8mUdam6Ev7teAwzpTB2XxfUTfVLrgRPXoEP5Iz0+XTWr1mMj4gM6L9Ksds2S41t5czaJmvqCCzABBQXHExrCU25pKrp3DqlUrVHfm2vVs/mX6ZzfVbFDtk/4fGX7eUwk="
    - secure: "Q3KKmkES4Xhd5GZx4Ltahgm4Bpt0hrfmVlu9eMW8NYSOkXANTaeh39NVmxfU0ll+uDw03UusGLcP1AHde0P41pzk3UMFH0PhArSZAd4+janoegETYFEcs0/BO/6Dy2vfM81BDLBB9Z22TwZtrirxiZ5VPsmmEyM7xyVkMEPUbfmTCGb8+hYE2D/BXZF6reBHTiBgSo5sLWGKu3iTbzW4XkyHLZIPyhhRKK3ho6IVYnBFD4Zd6NcyjpYaRYO2TB4f3ZEFrVrYj44JqStSGghfRytTwqY319L18JO7LxvnVpgQUh2SuTykdIT+rvknEOIJxIWgSz+dEnO4snsdpbw56IfeaMlRW6A+XyqoAGojgHDIzDDX3SGZGNHt7t6NgqlhARq//c5p2XSUuigJWoXXbm1DE1NVABQr9zr6F/Hmv4oGLU9yQwH5uupZCTsvC5QeBIDs1wLEekADootrgwGueUSgsEwtO74/T3o2j/RIdj9UJlidOJFCuB2aDYXChdPT/byLV7q3cx1dg6lrRa2UgniG9g1n8UseUa3kQTEHkRSGLFTfk8jUtDQaZoRyHnzLntS8F89ktMr/w4wa+sfJV1P1vKNwaii3ebSCbDYIC/vyoTL8IN1DUjgYrNw3+RCgV3Fh9UUJ7d8mHAkeUV2IOjPnhtpy4k+iXznZVyk9vJQ="
